services:
  - docker

install:
  - git clone --quiet --depth 1 https://github.com/mikaelarguedas/ros2ci.git .ros2ci

matrix:
  include:
    - env: JOB_TYPE=foxy
      script: .ros2ci/travis.bash $JOB_TYPE
    - env: JOB_TYPE=nightly
      script:
        - .ros2ci/travis.bash $JOB_TYPE
