name: Test neato_ros2_python
on: push

jobs:
  build_and_test:
    runs-on: ubuntu-20.04
    steps:
    - uses: ros-tooling/setup-ros@master
    - uses: ros-tooling/action-ros-ci@master
      with:
        package-name: neato_ros2_python 
